version: "3.8"
services:
  wallet_checker:
    build: .
    
    environment:
      - ELECTRUMX_SERVER_URL = "http://85.215.178.149:50002"
      - TELEGRAM_BOT_TOKEN=7706620947:AAGLGdTIKi4dB3irOtVmHD57f1Xxa8-ZIcs
      - TELEGRAM_CHAT_ID=1596333326
    deploy:
      replicas: 5  # 16 Instanzen für 16 Kerne
    
    volumes:
      - .:/app
    restart: unless-stopped
